/**
 * Common disposable / throwaway email domains. Not exhaustive — the real
 * line of defence is the MX-lookup check on the server. This list just
 * rejects the most egregious offenders client-side for fast UX feedback.
 *
 * Update periodically from upstream lists like disposable-email-domains
 * on GitHub. Kept static here so it doesn't require a network call.
 */
export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  '10minutemail.com', '10minutemail.net', '20minutemail.com',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org', 'guerrillamail.de',
  'guerrillamailblock.com', 'grr.la',
  'mailinator.com', 'mailinator.net', 'mailinator2.com',
  'temp-mail.org', 'temp-mail.io', 'temp-mail.de',
  'tempmail.com', 'tempmailo.com', 'tempmail.ninja', 'tempmail.plus',
  'throwawaymail.com', 'throwaway.email',
  'yopmail.com', 'yopmail.net', 'yopmail.fr', 'yopmail.gq',
  'sharklasers.com', 'spam4.me', 'spamgourmet.com', 'spamgourmet.net',
  'getnada.com', 'nada.email', 'nada.ltd',
  'trashmail.com', 'trashmail.net', 'trashmail.me', 'trashmail.io',
  'maildrop.cc', 'mailnesia.com', 'mailcatch.com',
  'fakeinbox.com', 'fakemail.net', 'fakemailgenerator.com',
  'dispostable.com', 'mytrashmail.com', 'mintemail.com',
  'emailondeck.com', 'mailsac.com', 'moakt.com', 'harakirimail.com',
  'mohmal.com', 'mailnator.com', 'mailexpire.com', 'tempinbox.com',
  'burnermail.io', 'inboxkitten.com', 'mailpoof.com',
  'guerrillamail.info', 'boun.cr', 'byom.de',
  'crazymailing.com', 'deadaddress.com', 'despammed.com',
  'devnullmail.com', 'discardmail.com', 'discardmail.de',
  'disposableaddress.com', 'disposableemailaddresses.emailmiser.com',
  'disposableinbox.com', 'dispose.it', 'dodgeit.com', 'dodsi.com',
  'drdrb.com', 'dropmail.me', 'dumpmail.de', 'e4ward.com',
  'emailigo.de', 'emailisvalid.com', 'emailsensei.com',
  'emailtemporario.com.br', 'ephemail.net', 'etranquil.com',
  'evopo.com', 'expirebox.com', 'fastacura.com',
  'filzmail.com', 'fixmail.tk', 'flyspam.com',
  'get-mail.cf', 'getairmail.com', 'gishpuppy.com',
  'great-host.in', 'greensloth.com', 'gsrv.co.uk',
  'haltospam.com', 'hotpop.com', 'hulapla.de',
  'ieatspam.eu', 'ieatspam.info', 'imails.info', 'inboxalias.com',
  'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'ipoo.org', 'irish2me.com', 'jetable.com', 'jetable.fr.nf',
  'jetable.net', 'jetable.org', 'kasmail.com', 'koszmail.pl',
  'kurzepost.de', 'lackmail.net', 'lhsdv.com', 'lifebyfood.com',
  'link2mail.net', 'litedrop.com', 'lol.ovpn.to', 'lookugly.com',
  'lortemail.dk', 'lr78.com', 'lroid.com', 'lukop.dk',
  'm21.cc', 'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net',
  'mail2rss.org', 'mail333.com', 'mailbidon.com', 'mailblocks.com',
  'mailcatch.com', 'maileater.com', 'mailexpire.com', 'mailforspam.com',
  'mailin8r.com', 'mailinator.com', 'mailinator.net', 'mailinator.org',
  'mailme.ir', 'mailme.lv', 'mailmetrash.com', 'mailmoat.com',
  'mailnull.com', 'mailshell.com', 'mailsiphon.com', 'mailslite.com',
  'mailzilla.com', 'mbx.cc', 'mega.zik.dj',
  'meltmail.com', 'mierdamail.com', 'ministry-of-silly-walks.de',
  'mt2015.com', 'mx0.wwwnew.eu', 'mypartyclip.de',
  'myzx.com', 'nervmich.net', 'nervtansen.de',
  'netmails.com', 'netmails.net', 'neverbox.com',
  'no-spam.ws', 'nobulk.com', 'noclickemail.com',
  'nogmailspam.info', 'nomail.xl.cx', 'nomail2me.com',
  'nomorespamemails.com', 'notmailinator.com', 'notsomuch.com',
  'nowmymail.com', 'nurfuerspam.de', 'nus.edu.sg',
  'objectmail.com', 'obobbo.com', 'odnorazovoe.ru',
  'oneoffemail.com', 'onewaymail.com', 'otherinbox.com',
  'ourklips.com', 'outlawspam.com', 'ovpn.to',
  'owlpic.com', 'pancakemail.com', 'pcusers.otherinbox.com',
  'pjjkp.com', 'plexolan.de', 'pookmail.com',
  'privacy.net', 'proxymail.eu', 'prtnx.com',
  'putthisinyouremail.com', 'qq.com', 'quickinbox.com',
  'rcpt.at', 'reallymymail.com', 'recode.me',
  'regbypass.com', 'regbypass.comsafe-mail.net', 'rejectmail.com',
  'rhyta.com', 'rklips.com', 'rmqkr.net',
  'rppkn.com', 'rtrtr.com', 's0ny.net',
  'safe-mail.net', 'safersignup.de', 'safetymail.info',
  'sandelf.de', 'saynotospams.com', 'scatmail.com',
  'schafmail.de', 'selfdestructingmail.com', 'sendspamhere.com',
  'shiftmail.com', 'shitmail.me', 'shortmail.net',
  'sibmail.com', 'skeefmail.com', 'slaskpost.se',
  'slipry.net', 'slopsbox.com', 'smashmail.de',
  'snoopstation.com', 'sofimail.com', 'sogetthis.com',
  'soodonims.com', 'spam.la', 'spam.su', 'spamavert.com',
  'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.ru',
  'spambox.info', 'spambox.irishspringrealty.com', 'spambox.us',
  'spamcannon.com', 'spamcannon.net', 'spamcero.com',
  'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net',
  'spamcowboy.org', 'spamday.com', 'spamex.com',
  'spamfighter.cf', 'spamfighter.ga', 'spamfighter.gq',
  'spamfighter.ml', 'spamfighter.tk', 'spamfree24.com',
  'spamfree24.de', 'spamfree24.eu', 'spamfree24.info',
  'spamfree24.net', 'spamfree24.org', 'spamgoes.in',
  'spamherelots.com', 'spamhereplease.com', 'spamhole.com',
  'spamify.com', 'spaminator.de', 'spamkill.info',
  'spaml.com', 'spaml.de', 'spammotel.com',
  'spamobox.com', 'spamoff.de', 'spamslicer.com',
  'spamspot.com', 'spamstack.net', 'spamthis.co.uk',
  'spamthisplease.com', 'spamtrail.com', 'spamtrap.ro',
  'superrito.com', 'suremail.info', 'svk.jp',
  'teleworm.us', 'thankyou2010.com', 'thc.st',
  'thinktimyer.com', 'thismail.net', 'tittbit.in',
  'tmail.ws', 'tmails.net', 'toiea.com',
  'tradermail.info', 'trash-amil.com', 'trash-mail.at',
  'trash-mail.com', 'trash-mail.de', 'trash2009.com',
  'trashemail.de', 'trashmail.at', 'trashymail.com',
  'trashymail.net', 'turual.com', 'twinmail.de',
  'tyldd.com', 'uggsrock.com', 'upliftnow.com',
  'uplipht.com', 'venompen.com', 'veryreallhemail.com',
  'vidchart.com', 'viditag.com', 'viewcastmedia.com',
  'vomoto.com', 'vpn.st', 'vsimcard.com',
  'vubby.com', 'wasteland.rfc822.org', 'webemail.me',
  'weg-werf-email.de', 'wegwerfadresse.de', 'wegwerfemail.com',
  'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.net',
  'wegwerfmail.org', 'wh4f.org', 'whyspam.me',
  'wickmail.net', 'wilemail.com', 'willhackforfood.biz',
  'willselfdestruct.com', 'winemaven.info', 'wronghead.com',
  'wuzup.net', 'wuzupmail.net', 'wwwnew.eu',
  'xagloo.com', 'xemaps.com', 'xents.com',
  'xjoi.com', 'xoxy.net', 'xyzfree.net',
  'yapped.net', 'yeah.net', 'yep.it',
  'yogamaven.com', 'yuurok.com', 'zehnminutenmail.de',
  'zippymail.info', 'zoaxe.com', 'zoemail.org',
]);

export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf('@');
  if (at < 0) return false;
  const domain = email.slice(at + 1).toLowerCase().trim();
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
